version: "3"

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - frontend
    
  client:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - "./front/:/app"
      - "/app/node_modules"
    networks:
      - frontend

networks: 
  frontend:
    driver: bridge